steps:
# build
- name: "gcr.io/cloud-builders/docker"
  args: ["build","-t","gcr.io/$PROJECT_ID/gcpdevops","."]
# push 
- name: "gcr.io/cloud-builders/docker"
  args: ["push","gcr.io/$PROJECT_ID/gcpdevops"]
# deploy 
- name: "gcr.io/cloud-builders/docker"
  args:
  - run
  - '-f'
  - 'gke.yaml'
  - --image=gcr.io/$PROJECT_ID/gcpdevops
  - --location=us-central1-c
  - --cluster=gcp-devops-project
  - --namespace=frontend