apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: frontend
    spec:
      containers:
      - image: frontend
        name: "gcr.io/gcp-repo/test-image:latest"
        ports:
        - containerPort: 80
        env:
          - name: PORT
            value: "80"
