apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: gcp-devops-project
  namespace: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  strategy: {}
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: gcr.io/massive-boulder-389916/gcpdevops@sha256:766a766a9dd3956a315be73055becf5ce7d6f2229857a428e29b09c905545aed
        name: gcp-devops-project
        ports:
        - containerPort: 80
        env:
          - name: PORT
            value: "80"

---
apiVersion: v1
kind: Service
metadata:
  name: gcp-devops-project-service
spec:
  selector:
    app.kubernetes.io/name: proxy
  ports:
  - name: gcp-devops-project-service
    protocol: TCP
    port: 80
    targetPort: 8080
    type: "LoadBalancer"