apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: gcp-devops-project
  namespace: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  strategy: {}
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: gcp-devops-project
        name: gcr.io/gcp-repo/test-gcpdevops:latest
        ports:
        - containerPort: 80
        env:
          - name: PORT
            value: "80"
